window.CAREERS_JOBS = [
  {
    id: 'protocol-engineer',
    slug: 'senior-blockchain-protocol-engineer',
    title: 'Senior Blockchain / Protocol Engineer',
    description: 'Lead the technical architecture of the Dracoin Cross-Chain Staking Platform across Ethereum, Solana, staking infrastructure and future cross-chain integrations.',
    department: 'Blockchain Engineering',
    employmentTypes: ['Full-Time', 'Contract', 'Consulting'],
    location: 'Remote',
    salary: '$170,000 – $210,000 USD/year',
    hourly: '$115 – $150 USD/hour',
    salaryMin: 170000,
    salaryMax: 210000,
    technologies: ['Ethereum', 'Solidity', 'EVM', 'Solana', 'Rust', 'DeFi', 'Security'],
    techDisplay: ['Ethereum/EVM', 'Solana', 'Solidity', 'Rust', 'DeFi', 'Staking', 'Blockchain architecture', 'Smart-contract security', 'Distributed systems'],
    assessment: 'engineering',
    responsibilities: [
      'Design and improve blockchain architecture.',
      'Review the existing platform.',
      'Design scalable blockchain adapters.',
      'Coordinate Ethereum and Solana development.',
      'Review smart contracts and blockchain programs.',
      'Design staking and reward architecture.',
      'Define engineering standards.',
      'Identify architectural risks.',
      'Support security reviews.',
      'Mentor blockchain engineers.',
      'Prepare architecture for future blockchain integrations.'
    ],
    required: [
      'Ethereum/EVM',
      'Solana',
      'Solidity',
      'Rust',
      'DeFi',
      'Staking',
      'Blockchain architecture',
      'Smart-contract security',
      'Distributed systems'
    ]
  },
  {
    id: 'solidity-evm',
    slug: 'senior-solidity-evm-engineer',
    title: 'Senior Solidity / EVM Engineer',
    description: 'Develop and maintain the Ethereum smart-contract infrastructure powering Dracoin staking.',
    department: 'Blockchain Engineering',
    employmentTypes: ['Full-Time', 'Contract', 'Consulting'],
    location: 'Remote',
    salary: '$150,000 – $180,000 USD/year',
    hourly: '$100 – $135 USD/hour',
    salaryMin: 150000,
    salaryMax: 180000,
    technologies: ['Ethereum', 'Solidity', 'EVM', 'DeFi', 'Security'],
    techDisplay: ['Solidity', 'Ethereum', 'EVM', 'ERC-20', 'OpenZeppelin', 'Foundry or Hardhat', 'DeFi', 'Smart-contract security'],
    assessment: 'engineering',
    responsibilities: [
      'Develop Solidity smart contracts.',
      'Implement staking.',
      'Implement unstaking.',
      'Implement rewards.',
      'Implement reward claims.',
      'Integrate ERC-20 tokens.',
      'Implement access control.',
      'Build comprehensive tests.',
      'Review existing contracts.',
      'Identify vulnerabilities.',
      'Optimize gas usage.',
      'Maintain documentation.',
      'Work with backend and security engineers.'
    ],
    required: [
      'Solidity',
      'Ethereum',
      'EVM',
      'ERC-20',
      'OpenZeppelin',
      'Foundry or Hardhat',
      'DeFi',
      'Smart-contract security'
    ]
  },
  {
    id: 'solana-rust',
    slug: 'senior-solana-rust-engineer',
    title: 'Senior Solana / Rust Engineer',
    description: 'Build and improve the Solana programs powering the Solana side of the Dracoin Cross-Chain Staking Platform.',
    department: 'Blockchain Engineering',
    employmentTypes: ['Full-Time', 'Contract', 'Consulting'],
    location: 'Remote',
    salary: '$155,000 – $190,000 USD/year',
    hourly: '$105 – $140 USD/hour',
    salaryMin: 155000,
    salaryMax: 190000,
    technologies: ['Solana', 'Rust', 'Anchor', 'DeFi'],
    techDisplay: ['Rust', 'Solana', 'Anchor', 'SPL Token', 'PDAs', 'CPIs', 'Solana testing', 'DeFi'],
    assessment: 'engineering',
    responsibilities: [
      'Develop Solana programs.',
      'Build staking functionality.',
      'Build reward functionality.',
      'Implement unstaking.',
      'Implement reward claims.',
      'Work with Rust and Anchor.',
      'Work with SPL tokens.',
      'Design PDAs.',
      'Implement CPIs.',
      'Build tests.',
      'Review Solana security.',
      'Integrate programs with backend systems.'
    ],
    required: [
      'Rust',
      'Solana',
      'Anchor',
      'SPL Token',
      'PDAs',
      'CPIs',
      'Solana testing',
      'DeFi'
    ]
  },
  {
    id: 'defi-protocol',
    slug: 'defi-protocol-engineer',
    title: 'DeFi / Protocol Engineer',
    description: 'Design the economic models behind staking pools, reward mechanisms and protocol incentives.',
    department: 'Protocol / DeFi',
    employmentTypes: ['Full-Time', 'Contract', 'Consulting'],
    location: 'Remote',
    salary: '$145,000 – $180,000 USD/year',
    hourly: '$95 – $130 USD/hour',
    salaryMin: 145000,
    salaryMax: 180000,
    technologies: ['DeFi', 'Ethereum', 'Solana', 'Security'],
    techDisplay: ['DeFi', 'Staking', 'Tokenomics', 'Reward systems', 'APR/APY', 'Financial modeling', 'Protocol design', 'Smart-contract understanding'],
    assessment: 'engineering',
    responsibilities: [
      'Design staking models.',
      'Design reward mechanisms.',
      'Develop APR/APY models.',
      'Design staking pool parameters.',
      'Analyze incentives.',
      'Develop reward-distribution models.',
      'Model lock periods.',
      'Analyze protocol economics.',
      'Identify economic attack vectors.',
      'Perform reward simulations.',
      'Work with blockchain engineers.'
    ],
    required: [
      'DeFi',
      'Staking',
      'Tokenomics',
      'Reward systems',
      'APR/APY',
      'Financial modeling',
      'Protocol design',
      'Smart-contract understanding'
    ]
  },
  {
    id: 'backend',
    slug: 'blockchain-backend-engineer',
    title: 'Blockchain Backend Engineer',
    description: 'Build the backend infrastructure connecting Ethereum, Solana, blockchain data, APIs, databases and the Dracoin Web3 frontend.',
    department: 'Backend Engineering',
    employmentTypes: ['Full-Time', 'Contract', 'Consulting'],
    location: 'Remote',
    salary: '$130,000 – $165,000 USD/year',
    hourly: '$85 – $115 USD/hour',
    salaryMin: 130000,
    salaryMax: 165000,
    technologies: ['Node.js', 'TypeScript', 'PostgreSQL', 'Docker', 'Ethereum', 'Solana'],
    techDisplay: ['Node.js', 'TypeScript', 'REST APIs', 'PostgreSQL', 'Ethereum RPC', 'Solana RPC', 'Blockchain indexing', 'Web3 libraries', 'Docker', 'Automated testing'],
    assessment: 'engineering',
    responsibilities: [
      'Develop backend APIs.',
      'Build blockchain integration services.',
      'Integrate Ethereum RPC.',
      'Integrate Solana RPC.',
      'Develop blockchain adapters.',
      'Build staking APIs.',
      'Build reward APIs.',
      'Build wallet APIs.',
      'Build transaction services.',
      'Develop blockchain indexing.',
      'Process blockchain events.',
      'Develop background workers.',
      'Implement transaction monitoring.',
      'Implement reconciliation.',
      'Design PostgreSQL architecture.',
      'Implement caching.',
      'Build analytics APIs.',
      'Build administration APIs.'
    ],
    required: [
      'Node.js',
      'TypeScript',
      'REST APIs',
      'PostgreSQL',
      'Ethereum RPC',
      'Solana RPC',
      'Blockchain indexing',
      'Web3 libraries',
      'Docker',
      'Automated testing'
    ]
  },
  {
    id: 'frontend',
    slug: 'web3-frontend-engineer',
    title: 'Web3 Frontend Engineer',
    description: 'Build the user-facing staking experience across Ethereum and Solana.',
    department: 'Frontend Engineering',
    employmentTypes: ['Full-Time', 'Contract', 'Consulting'],
    location: 'Remote',
    salary: '$120,000 – $155,000 USD/year',
    hourly: '$75 – $105 USD/hour',
    salaryMin: 120000,
    salaryMax: 155000,
    technologies: ['React', 'Next.js', 'TypeScript', 'Ethereum', 'Solana'],
    techDisplay: ['React', 'Next.js', 'TypeScript', 'JavaScript', 'Web3', 'Ethereum wallet integration', 'Solana wallet integration', 'REST APIs', 'Responsive UI'],
    preferred: ['wagmi', 'viem', 'Solana Wallet Adapter', 'Tailwind CSS', 'DeFi frontend experience'],
    assessment: 'engineering',
    responsibilities: [
      'Build staking dashboard.',
      'Implement Ethereum wallet integration.',
      'Implement Solana wallet integration.',
      'Build staking interfaces.',
      'Build unstaking interfaces.',
      'Build reward interfaces.',
      'Display staking positions.',
      'Display transaction status.',
      'Display wallet balances.',
      'Build analytics interfaces.',
      'Implement loading and error states.',
      'Build responsive Web3 UI.',
      'Integrate frontend with backend APIs.'
    ],
    required: [
      'React',
      'Next.js',
      'TypeScript',
      'JavaScript',
      'Web3',
      'Ethereum wallet integration',
      'Solana wallet integration',
      'REST APIs',
      'Responsive UI'
    ]
  },
  {
    id: 'security',
    slug: 'blockchain-security-engineer',
    title: 'Blockchain Security Engineer',
    description: 'Protect the Dracoin platform across smart contracts, Solana programs, backend services and future cross-chain infrastructure.',
    department: 'Security',
    employmentTypes: ['Full-Time', 'Contract', 'Consulting'],
    location: 'Remote',
    salary: '$160,000 – $210,000 USD/year',
    hourly: '$120 – $175 USD/hour',
    salaryMin: 160000,
    salaryMax: 210000,
    technologies: ['Security', 'Ethereum', 'Solidity', 'EVM', 'Solana', 'Rust', 'DeFi'],
    techDisplay: ['Solidity security', 'EVM security', 'Solana security', 'Rust', 'DeFi security', 'Threat modeling', 'Vulnerability assessment', 'Security testing'],
    assessment: 'engineering',
    responsibilities: [
      'Review Ethereum smart contracts.',
      'Review Solana programs.',
      'Perform threat modeling.',
      'Review staking logic.',
      'Review reward calculations.',
      'Review access control.',
      'Analyze wallet security.',
      'Identify attack vectors.',
      'Perform security testing.',
      'Review backend security.',
      'Review indexing security.',
      'Review cross-chain architecture.',
      'Produce security reports.',
      'Verify remediation.'
    ],
    required: [
      'Solidity security',
      'EVM security',
      'Solana security',
      'Rust',
      'DeFi security',
      'Threat modeling',
      'Vulnerability assessment',
      'Security testing'
    ]
  },
  {
    id: 'qa',
    slug: 'blockchain-qa-test-engineer',
    title: 'Blockchain QA / Test Engineer',
    description: 'Ensure the Dracoin platform operates correctly across smart contracts, Solana programs, backend services, frontend applications and blockchain infrastructure.',
    department: 'QA',
    employmentTypes: ['Full-Time', 'Contract', 'Consulting'],
    location: 'Remote',
    salary: '$105,000 – $140,000 USD/year',
    hourly: '$65 – $95 USD/hour',
    salaryMin: 105000,
    salaryMax: 140000,
    technologies: ['Ethereum', 'Solana', 'TypeScript', 'Security'],
    techDisplay: ['Software testing', 'Blockchain testing', 'API testing', 'JavaScript/TypeScript', 'Automated testing', 'Smart-contract testing', 'Ethereum', 'Solana', 'Git/GitHub'],
    assessment: 'engineering',
    responsibilities: [
      'Develop blockchain test plans.',
      'Test Ethereum contracts.',
      'Test Solana programs.',
      'Test staking.',
      'Test unstaking.',
      'Test reward calculations.',
      'Test reward claims.',
      'Test wallet connections.',
      'Test transactions.',
      'Test blockchain indexing.',
      'Test backend APIs.',
      'Test frontend.',
      'Test RPC failures.',
      'Test duplicate blockchain events.',
      'Test transaction failures.',
      'Develop automated tests.',
      'Perform regression testing.'
    ],
    required: [
      'Software testing',
      'Blockchain testing',
      'API testing',
      'JavaScript/TypeScript',
      'Automated testing',
      'Smart-contract testing',
      'Ethereum',
      'Solana',
      'Git/GitHub'
    ]
  },
  {
    id: 'devops',
    slug: 'blockchain-devops-infrastructure-engineer',
    title: 'Blockchain DevOps / Infrastructure Engineer',
    description: 'Build and maintain reliable infrastructure for the Dracoin application, APIs, indexers, blockchain integrations and monitoring systems.',
    department: 'DevOps',
    employmentTypes: ['Full-Time', 'Contract', 'Consulting'],
    location: 'Remote',
    salary: '$130,000 – $170,000 USD/year',
    hourly: '$85 – $120 USD/hour',
    salaryMin: 130000,
    salaryMax: 170000,
    technologies: ['Docker', 'Cloud', 'Ethereum', 'Solana'],
    techDisplay: ['Linux', 'Docker', 'CI/CD', 'AWS/GCP/Azure', 'Cloud infrastructure', 'Monitoring', 'Blockchain infrastructure', 'RPC', 'Git/GitHub'],
    preferred: ['Kubernetes', 'Terraform', 'Infrastructure as Code', 'Prometheus/Grafana', 'Cloud security'],
    assessment: 'engineering',
    responsibilities: [
      'Design cloud infrastructure.',
      'Deploy backend services.',
      'Deploy blockchain indexers.',
      'Manage Ethereum RPC.',
      'Manage Solana RPC.',
      'Build CI/CD pipelines.',
      'Manage Docker.',
      'Configure monitoring.',
      'Configure logging.',
      'Manage secrets.',
      'Configure backups.',
      'Monitor blockchain synchronization.',
      'Monitor backend services.',
      'Implement health checks.',
      'Support testnet infrastructure.',
      'Prepare production infrastructure.',
      'Develop disaster recovery procedures.'
    ],
    required: [
      'Linux',
      'Docker',
      'CI/CD',
      'AWS/GCP/Azure',
      'Cloud infrastructure',
      'Monitoring',
      'Blockchain infrastructure',
      'RPC',
      'Git/GitHub'
    ]
  },
  {
    id: 'project-manager',
    slug: 'web3-project-manager',
    title: 'Web3 Project Manager',
    description: 'Coordinate the engineering, security, QA, infrastructure and product teams responsible for delivering the Dracoin Cross-Chain Staking Platform.',
    department: 'Project Management',
    employmentTypes: ['Full-Time', 'Contract', 'Consulting'],
    location: 'Remote',
    salary: '$110,000 – $150,000 USD/year',
    hourly: '$70 – $110 USD/hour',
    salaryMin: 110000,
    salaryMax: 150000,
    technologies: ['DeFi'],
    techDisplay: ['Project management', 'Software development projects', 'Agile/Scrum', 'Communication', 'Organization', 'Jira/Linear/Notion/GitHub Projects'],
    preferred: ['Web3 experience', 'DeFi knowledge', 'Ethereum knowledge', 'Solana knowledge', 'Smart-contract understanding', 'Software architecture understanding'],
    assessment: 'pm',
    responsibilities: [
      'Create project roadmap.',
      'Manage development milestones.',
      'Coordinate blockchain engineers.',
      'Coordinate backend development.',
      'Coordinate frontend development.',
      'Coordinate QA.',
      'Coordinate security.',
      'Coordinate DevOps.',
      'Manage sprints.',
      'Track dependencies.',
      'Track blockers.',
      'Manage risks.',
      'Organize meetings.',
      'Track deliverables.',
      'Coordinate testnet releases.',
      'Coordinate production readiness.',
      'Maintain project documentation.',
      'Report project progress.'
    ],
    required: [
      'Project management',
      'Software development projects',
      'Agile/Scrum',
      'Communication',
      'Organization',
      'Jira/Linear/Notion/GitHub Projects'
    ]
  }
];

window.findCareersJob = function (key) {
  if (!key) return null;
  var value = String(key).toLowerCase();
  var jobs = window.CAREERS_JOBS || [];
  for (var i = 0; i < jobs.length; i += 1) {
    if (jobs[i].id === value || jobs[i].slug === value) return jobs[i];
  }
  return null;
};
